### PR TITLE
Rebase of shootout benchmarks + port to WASI

### PR DESCRIPTION
**Pull request by fitzgen**
Haven't made them take input via I/O yet, but I added licenses.

Supersedes #80; sorry for the churn.

### CODE REVIEW

**Comment by fitzgen** [comment]
I think we can merge this now, and then do the inputs-via-I/O work after it lands.

**Review by abrown — APPROVED** [review]

**Comment by jedisct1** [comment]
Err... with the exception of `ackermann` and `fib2`, I wrote these benchmarks, not Isaac Gouy :)

**Comment by fitzgen** [comment]
> Err... with the exception of `ackermann`, `fib2`, `heapsort` and `matrix`, I wrote these benchmarks, not Isaac Gouy :)

Oh! I was under the impression that they were taken from the benchmarks game! Am I misunderstanding and you created these solutions yourself?

**Comment by jedisct1** [comment]
Yes, I wrote these for sightglass.

**Comment by abrown** [comment]
What license do you want to release those under? Dual MIT-Apache?

**Comment by jedisct1** [comment]
Yep, for consistency, dual MIT-Apache is probably best.

**Pull request merged**
