### PR TITLE
sightglass-next: Add support for using small workloads

### PR DESCRIPTION
**Pull request by fitzgen**
Pass the `--small-workloads` flag to set the `WASM_BENCH_USE_SMALL_WORKLOAD` env var so that benchmark programs can use smaller, faster-to-execute inputs, if they have them available. I added small workloads for the blake3 programs.

### CODE REVIEW

**Comment by fitzgen** [comment]
Fixes #70

**Comment by fitzgen** [comment]
Hm looks like building the ackermann program doesn't use WASI's stat, but something else (I'm assuming it is emscripten's internal syscall).

I can split that last commit out into a new PR so that we don't hold up the rest of this stuff.

**Comment by fitzgen** [comment]
Getting the C benchmarks working requires using wasi-sdk in docker instead of emscripten.

**Comment by fitzgen** [comment]
I have the ackermann benchmark working with wasi-sdk, but the blake3-simd benchmark is proving difficult.

**Review by abrown — APPROVED** [review]

**Comment by abrown** [comment]
ci: blake-scalar is not finding `default.input`?

**Comment by fitzgen** [comment]
Hm, interesting... it runs fine locally :thinking:

**Comment by fitzgen** [comment]
I think the issue was building the default wasmtime engine via docker, which had previously been happening in child processes and was using a relative path to the dockerfile, and now that the child processes are in a different working directory, that relative path broke. The fix is to build engines up front, before we spawn child processes.

**Comment by fitzgen** [comment]
Gah, no, that was a different bug. Still hunting down the CI bug...

**Comment by fitzgen** [comment]
Okay, I've got this green in CI now, but it needs https://github.com/bytecodealliance/wasmtime/pull/2612 to merge before I can remove the "TEMP" commit.

**Comment by fitzgen** [comment]
Now that the wasmtime PR merged this should be good to merge.

**Pull request merged**
