### PR TITLE
Removes define of NDEBUG to allow asserts to work

### PR DESCRIPTION
**Pull request by jlb6740**

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
Nice!

**Comment by abrown** [comment]
The `benchmarks/run` CI task should be green if we rebase this on #243. But to get the `benchmarks/rebuild` task to work I think we may need to rebuild all of the benchmarks and check them back in to Git. Changing how we build the benchmarks will change the output WebAssembly and that is what that `benchmarks/rebuild` is doing--ensuring we build the same bytes in CI as we would locally.

**Comment by abrown** [comment]
(or maybe ripping out `NDEBUG` doesn't affect the WebAssembly output?!?)

**Comment by jlb6740** [comment]
Yes, if we modify the dockerfile used to build the benchmarks then all the wasm benchmarks that use that file should be checked in as well. I can submit a patch on top of this one that does that.

**Comment by jlb6740** [comment]
Issue first discovered #238

**Pull request merged**
