### PR TITLE
Update wasmparser to 0.86

### PR DESCRIPTION
**Pull request by yurydelendik**
I was not able to compile some of the new benchmarks I was trying to submit. I think it was due to new (SIMD?) instructions. Updating of wasmparser helped.

P.S. weird modifications in cargo.lock

### CODE REVIEW

**Comment by abrown** [comment]
Maybe let's merge #187 first... Might resolve some of that weirdness.

**Comment by abrown** [comment]
Ok, #187 is merged... I'm surprised this doesn't need a rebase?

**Comment by yurydelendik** [comment]
> Ok, #187 is merged... I'm surprised this doesn't need a rebase?

Perhaps it is doing the same changed to the lock file.

**Comment by abrown** [comment]
I think you're right, from glancing through the diff.

**Review by abrown — APPROVED** [review]

**Pull request merged**
